# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eMEHV9DlaAxkAwRSnUlQ5kzamDD-YBBr
"""

p= 'hello'
print(p)